### ISSUE TITLE
Please relax Faraday on 1.x branch

### ISSUE THREAD

**Issue by magni-** [librato/librato-metrics#142]
Faraday is currently locked at 0.7, which triggers warnings on Ruby 2.7. Those warnings [were fixed in Faraday 0.17.1](https://github.com/lostisland/faraday/blob/master/CHANGELOG.md#v0171), but those of us who [cannot upgrade to Librato 2.1](https://www.librato.com/docs/kb/faq/account_questions/tags_or_sources/) have no way to upgrade.

I have a branch off of the `v1.6.1` tag [here](https://github.com/librato/librato-metrics/compare/v1.6.1...magni-:pp/relax-faraday), but since there is no branch, just the tag, I cannot open a PR.

**Comment by irphilli** [comment]
+1 - And, if at all possible, would recommend supporting faraday 1.0.

**Comment by jasonrudolph** [comment]
+1

I have a [branch](https://github.com/jasonrudolph/librato-metrics/tree/librato-metrics-1.x-plus-ruby-2.7) that resolves an issue running the tests in v1.6.1 and upgrades faraday to `~> 1.0`: https://github.com/jasonrudolph/librato-metrics/compare/v1.6.1...d28759c913d8687a9352f92e6fddf0edcf2ca242

Would love to see a 1.x branch opened so that @magni- or I could submit this as a pull request. @chancefeick: Do you happen to know who might be able to help out with this? 🙏

**Comment by akahn** [comment]
I've pushed up a 1.x branch based on v1.6.1. Feel free to open pull requests. Thank you for raising this issue.

**Comment by jasonrudolph** [comment]
Thanks, @akahn. I've opened https://github.com/librato/librato-metrics/pull/143 with a proposed update for addressing this issue.

**Comment by akahn** [comment]
Please go ahead and update your applications to use this git tag https://github.com/librato/librato-metrics/tree/v1.6.2 I'm working on pushing a new release to rubygems.org as well, but this may take some time.

**Comment by akahn** [comment]
The new gem is now on rubygems https://rubygems.org/gems/librato-metrics/versions/1.6.2

**Comment by jasonrudolph** [comment]
Thanks, @akahn! :bow: :zap:
